### --------------- Auth Routes ---------------
# @name login
POST http://localhost:8080/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "CoolUser1",
    "password": "notgoodpass"
}

###
@jwtAuthToken = {{ login.response.body.$ }} 
POST http://localhost:8080/auth/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwtAuthToken}}

###
GET http://localhost:8080/auth/testing HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwtAuthToken}}

### --------------- Player Routes ---------------
GET http://localhost:8080/players/all HTTP/1.1
Content-Type: application/json


###
GET http://localhost:8080/players/5 HTTP/1.1
Content-Type: application/json

### 

POST http://localhost:8080/players/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwtAuthToken}}

{
    "username": "Jimmy2"
}

### --------------- Game Routes ---------------
GET http://localhost:8080/games/all HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8080/games/create HTTP/1.1
Content-Type: application/json

{
    "name": "Ping Pong"
}

### --------------- Match Routes ---------------
GET http://localhost:8080/matches/all HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8080/matches/1 HTTP/1.1

###

GET http://localhost:8080/matches/search?playerId=2 HTTP/1.1
Content-Type: application/json
